#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path


NO_USABLE_COUNTS_EXIT_CODE = 100
DIAGNOSTIC_FILENAME = "no_usable_counts.json"
RUN_TOKEN_ENV = "UNISCFLOW_MAPPER_RUN_TOKEN"


def no_aligned_reads_reason(out_dir: Path, samtools: str) -> str | None:
    # Only diagnose a completed zero-alignment run; leave all other paths unchanged.
    fields = (
        "Number of input reads",
        "Uniquely mapped reads number",
        "Number of reads mapped to multiple loci",
        "Number of reads mapped to too many loci",
    )
    try:
        values = {}
        finished = False
        for line in (out_dir / "Log.final.out").read_text().splitlines():
            key, separator, value = line.partition("|")
            key, value = key.strip(), value.strip()
            if not separator:
                continue
            if key == "Finished on" and value:
                finished = True
            if key in fields:
                if key in values or re.fullmatch(r"[0-9]+", value) is None:
                    return None
                values[key] = int(value)
        if not finished or set(values) != set(fields) or any(values[key] for key in fields[1:]):
            return None
        log = (out_dir / "Log.out").read_text()
        if "ALL DONE!" not in log or "FATAL" in log:
            return None
        bam = out_dir / "Aligned.sortedByCoord.out.bam"
        if not bam.is_file() or bam.stat().st_size == 0:
            return None
        check = subprocess.run(
            [samtools, "quickcheck", str(bam)], capture_output=True, text=True, timeout=120,
        )
        if check.returncode != 0:
            return None
        count = subprocess.run(
            [samtools, "view", "-c", "-F", "4", str(bam)],
            capture_output=True, text=True, timeout=120,
        )
        if count.returncode != 0 or count.stdout.strip() != "0":
            return None
    except (OSError, UnicodeError, ValueError, subprocess.TimeoutExpired):
        return None
    return (
        "no_usable_counts: STAR completed successfully but no mapped reads are available "
        "for counting; "
        f"STAR_input_reads={values[fields[0]]}; STAR_uniquely_mapped_reads=0; "
        "STAR_multimapped_reads=0; BAM_mapped_records=0. "
        "Stopped before featureCounts; no count matrix was generated by this run. "
        "Review input depth, reference species/assembly, and read layout; "
        "retain the source inputs and STAR diagnostic outputs."
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Diagnose completed STAR runs with no alignments to count.")
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--samtools", default="samtools")
    args = parser.parse_args()
    reason = no_aligned_reads_reason(args.output_dir, args.samtools)
    if reason is None:
        return 0
    diagnostic = {
        "code": "no_usable_counts",
        "run_token": os.environ.get(RUN_TOKEN_ENV, ""),
        "reason": reason,
        "stage": "pre_featurecounts",
        "star_completed": True,
        "bam_integrity_checked": True,
        "bam_mapped_records": 0,
    }
    (args.output_dir / DIAGNOSTIC_FILENAME).write_text(json.dumps(diagnostic, indent=2) + "\n")
    print(f"[uniscflow] {reason}", file=sys.stderr, flush=True)
    return NO_USABLE_COUNTS_EXIT_CODE


if __name__ == "__main__":
    raise SystemExit(main())
