from __future__ import annotations

import copy
import unittest

from test_scope_regressions import load_legacy_module


CELLRANGER = ("FASTQ files were processed with 10x Genomics' Cell Ranger analysis pipelines. "
              "The read count matrix generated by CellRanger was then analyzed using Seurat v5.0.2.")
PSEUDOBULK = ("A pseudobulk method was applied to investigate gene expression among different conditions "
              "at the population level. Specifically, the raw gene counts of each sample were extracted "
              "and compared with DESeq2.")
HTSEQ = "Gene counts generated with HTSeq-count (v0.9.1). Raw gene counts of each sample are provided."


class PseudobulkSampleOutputTests(unittest.TestCase):
    """A pseudobulk aggregation statement must not count as bulk sample-level quantification."""

    def setUp(self):
        self.infer = load_legacy_module("infer_platform")

    def fields(self, processing):
        return {
            "!Sample_title": ["C3H dual-lineage receiver, Day 3, No ligand, rep 2"],
            "!Sample_characteristics_ch1": ["cell line: c3h/10t1/2", "treatment: No ligand"],
            "!Sample_molecule_ch1": ["total RNA"],
            "!Sample_library_strategy": ["RNA-Seq"],
            "!Sample_library_source": ["transcriptomic"],
            "!Sample_extract_protocol_ch1": [
                "cells were trypsinized and lysed to isolate individual nuclei.",
                "Library construction was performed according to the manufacturer's protocol "
                "(10x Genomics single cell 3' v3.1 protocol).",
            ],
            "!Sample_data_processing": processing,
        }

    def audit(self, fields):
        samples = {"GSM1": fields, "GSM2": copy.deepcopy(fields)}
        samples["GSM2"]["!Sample_title"] = ["C3H dual-lineage receiver, Day 3, GFP ligand rows, rep 2"]
        _, keys = self.infer.shared_sample_protocol_context(samples, list(samples))
        return self.infer.conventional_bulk_sample_context(
            self.infer.sample_route_local_field_groups(fields, keys),
            self.infer.sample_route_shared_field_groups(fields, keys),
        )

    def test_pseudobulk_statement_is_not_sample_quantification(self):
        audit = self.audit(self.fields([CELLRANGER, PSEUDOBULK]))
        self.assertFalse(audit["decisive"], audit)
        self.assertEqual(audit["sample_quantification_evidence"], [])

    def test_pseudobulk_pattern_spellings(self):
        for text in ("pseudobulk", "pseudo-bulk", "Pseudo bulk", "pseudobulked"):
            self.assertIsNotNone(self.infer.PSEUDOBULK_AGGREGATION_PATTERN.search(f"A {text} analysis"), text)
        self.assertIsNone(self.infer.PSEUDOBULK_AGGREGATION_PATTERN.search("bulk RNA-seq of pseudo-replicates"))

    def test_conventional_per_sample_counts_still_decisive(self):
        fields = self.fields([HTSEQ])
        fields["!Sample_extract_protocol_ch1"] = [
            "Total RNA was extracted with TRIzol and libraries were prepared with the Illumina TruSeq stranded mRNA kit.",
        ]
        audit = self.audit(fields)
        self.assertTrue(audit["decisive"], audit)
        self.assertTrue(audit["sample_quantification_evidence"])


if __name__ == "__main__":
    unittest.main()
